export const SET_AUTHENTIFICATION = "SET_AUTHENTIFICATION";
export const INCREMENT_ACTION_COUNT = "INCREMENT_ACTION_COUNT";
export const ADD_RESSOURCE = "ADD_RESSOURCE";
export const PARSE_MESSAGE = "PARSE_MESSAGE";
export const PARSE_ERROR = "PARSE_ERROR";
export const RESET_ERROR = "RESET_ERROR";
